### ISSUE TITLE
AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by simonw** [myles/mastodon-to-sqlite#10]
I got this error running:

    mastodon-to-sqlite followers mastodon.db

Full trace below:

```
Importing followers  [#-----------------------------------]  11760
Traceback (most recent call last):
  File "/Users/simon/.local/bin/mastodon-to-sqlite", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/mastodon_to_sqlite/cli.py", line 112, in followers
    service.save_accounts(db, followers, follower_id=account_id)
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/mastodon_to_sqlite/service.py", line 196, in save_accounts
    transformer_account(account)
  File "/Users/simon/.local/pipx/venvs/mastodon-to-sqlite/lib/python3.11/site-packages/mastodon_to_sqlite/service.py", line 173, in transformer_account
    for k in account.keys()
             ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by simonw** [comment]
It looks like the command mostly worked though - I now have a database with a bunch of records in it:
```
% sqlite-utils tables mastodon.db --counts
[{"table": "accounts", "count": 11761},
 {"table": "accounts_fts", "count": 11761},
 {"table": "accounts_fts_data", "count": 716},
 {"table": "accounts_fts_idx", "count": 634},
 {"table": "accounts_fts_docsize", "count": 11761},
 {"table": "accounts_fts_config", "count": 1},
 {"table": "following", "count": 11760},
 {"table": "statuses", "count": 0},
 {"table": "statuses_fts", "count": 0},
 {"table": "statuses_fts_data", "count": 2},
 {"table": "statuses_fts_idx", "count": 0},
 {"table": "statuses_fts_docsize", "count": 0},
 {"table": "statuses_fts_config", "count": 1},
 {"table": "status_activities", "count": 0}]
```

**Comment by simonw** [comment]
I have 16,000 followers and this cut off at 11,761 - but I'm running it a second time and it made it all the way to the end.

My best guess is that an error was returned - maybe late limiting? And as a result the `account` variable in Python was a string rather than a dictionary.

**Comment by simonw** [comment]
I just got a similar error running the `statuses` command:

```
% python -i $(which mastodon-to-sqlite) statuses mastodon.db -a ../auth.json
Importing statuses  [-#----------------------------------]  2880
Traceback (most recent call last):
...
  File "/private/tmp/mastodon-to-sqlite/mastodon_to_sqlite/cli.py", line 186, in statuses
    service.save_statuses(db, statuses)
  File "/private/tmp/mastodon-to-sqlite/mastodon_to_sqlite/service.py", line 252, in save_statuses
    transformer_status(status)
  File "/private/tmp/mastodon-to-sqlite/mastodon_to_sqlite/service.py", line 230, in transformer_status
    account = status.pop("account")
              ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'pop'
>>> import pdb
>>> pdb.pm()
> /private/tmp/mastodon-to-sqlite/mastodon_to_sqlite/service.py(230)transformer_status()
-> account = status.pop("account")
(Pdb) status
'error'
```
I popped up the stack a bit and found:
```
(Pdb) statuses
{'error': 'Too many requests'}
```

**Comment by simonw** [comment]
Here's where the error originated:

https://github.com/myles/mastodon-to-sqlite/blob/cd7352b410a977f4b065de9057611308638f3045/mastodon_to_sqlite/service.py#L215-L222

It looks like that `response.json()` can in some circumstances return `{"error": "Too many requests"}`.

Maybe it should spot that and retry up to 3 times with an increasing gap in between each retry?

**Comment by simonw** [comment]
Looks like all of these methods eventually go through `request_paginated()`:

https://github.com/myles/mastodon-to-sqlite/blob/cd7352b410a977f4b065de9057611308638f3045/mastodon_to_sqlite/client.py#L42-L65

So that might be the right place to put in some limited retry logic.

**Comment by myles** [comment]
Thanks for reporting, issue has been fixed.
